package com.example.composeapp

const val HOME_NAVIGATION_ID = "home"
const val APPOINTMENT_NAVIGATION_ID = "appointment"
const val SHOP_NAVIGATION_ID = "shop"
const val PROFILE_NAVIGATION_ID = "profile"
const val AUTHORIZATION = "Authorization"
const val TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoVHlwZSI6InVzZXJzIiwiZW1haWwiOiI5OTYyNjcwNzdAcXEuY29tIiwiaWQiOiJiOWFjNzZiYy0wMjBjLTQyOWUtOTVmZi02MGU2NmE4NzZlZjAiLCJrZXlfaWQiOiI3OTkwYzBhNjM1ODg0ODMyOTgwMzc4ZWZlNzkzZTQxZSIsImVwb2NoIjoxNjQxMTk4NzI1LCJwYXJ0bmVyX25hbWUiOiJhbmRyb2lkLWFwcCIsInR5cGUiOjAsImlhdCI6MTY0MTE5ODEyNSwiZXhwIjoxNjQxMjAxNzI1fQ.qBFEW8MBk9rDUz0TJj54ltinydra7ahZ3F_LOe6-Zo8"

const val LOGIN_NAVIGATION_ID = "login"
const val NETWORK_RESPONSE_STATUS_OK = 200