package com.example.composeapp

const val HOME_NAVIGATION_ID = "home"
const val APPOINTMENT_NAVIGATION_ID = "appointment"
const val SHOP_NAVIGATION_ID = "shop"
const val PROFILE_NAVIGATION_ID = "profile"
const val AUTHORIZATION = "Authorization"
const val TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoVHlwZSI6InVzZXJzIiwiZW1haWwiOiI5OTYyNjcwNzdAcXEuY29tIiwiaWQiOiJiOWFjNzZiYy0wMjBjLTQyOWUtOTVmZi02MGU2NmE4NzZlZjAiLCJrZXlfaWQiOiI3OTkwYzBhNjM1ODg0ODMyOTgwMzc4ZWZlNzkzZTQxZSIsImVwb2NoIjoxNjQwOTU5NzIzLCJwYXJ0bmVyX25hbWUiOiJhbmRyb2lkLWFwcCIsInR5cGUiOjAsImlhdCI6MTY0MDk1OTEyMywiZXhwIjoxNjQwOTYyNzIzfQ.G7d8plMFz5VyFePO9cNLheYNThSQVY5Zup_KDZ_htzM"

const val LOGIN_NAVIGATION_ID = "login"
const val NETWORK_RESPONSE_STATUS_OK = 200