package com.example.composeapp

const val HOME_NAVIGATION_ID = "home"
const val APPOINTMENT_NAVIGATION_ID = "appointment"
const val SHOP_NAVIGATION_ID = "shop"
const val PROFILE_NAVIGATION_ID = "profile"
const val AUTHORIZATION = "Authorization"
const val TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoVHlwZSI6InVzZXJzIiwiZW1haWwiOiI5OTYyNjcwNzdAcXEuY29tIiwiaWQiOiJiOWFjNzZiYy0wMjBjLTQyOWUtOTVmZi02MGU2NmE4NzZlZjAiLCJrZXlfaWQiOiI3OTkwYzBhNjM1ODg0ODMyOTgwMzc4ZWZlNzkzZTQxZSIsImVwb2NoIjoxNjQxMDk1MzQyLCJwYXJ0bmVyX25hbWUiOiJhbmRyb2lkLWFwcCIsInR5cGUiOjAsImlhdCI6MTY0MTA5NDc0MiwiZXhwIjoxNjQxMDk4MzQyfQ._CIx4ZlLe9jgGPUWFOAgON1UeDSb6EZ_viJY3TVwGpQ"

const val LOGIN_NAVIGATION_ID = "login"
const val NETWORK_RESPONSE_STATUS_OK = 200